# serverless.yml

service: cube-builder

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    zip: true

provider:
  name: aws
  runtime: python3.6
  stage: prod
  region: us-east-1

  environment:
    KEY_ID: CHANGE_ME
    SECRET_KEY: CHANGE_ME
    RDS_HOST: CHANGE_ME
    RDS_DBNAME: CHANGE_ME
    RDS_USER: CHANGE_ME
    RDS_PASSWORD: CHANGE_ME
    URL_STAC: CHANGE_ME
    BUCKET_NAME: CHANGE_ME
    LAMBDA_FUNCTION_NAME: ${self:service}-${self:provider.stage}-app
    QUEUE_NAME: cubeBuilderQueue
    KINESIS_NAME: cubeBuilderKinesis
    DYNAMO_TB_ACTIVITY: CHANGE_ME
    DBNAME_TB_CONTROL: CHANGE_ME
    ENABLE_OBT_OAUTH: 0
    AUTH_CLIENT_SECRET_KEY: CHANGE_ME
    AUTH_CLIENT_AUDIENCE: CHANGE_ME

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:GetQueueUrl
        - sqs:ListQueues
      Resource:
        - Fn::GetAtt:
          - cubeBuilderQueue
          - Arn

    - Effect: "Allow"
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:GetQueueUrl
        - sqs:ListQueues
      Resource:
        - Fn::GetAtt:
          - cubeBuilderQueueDLQ
          - Arn
          
    - Effect: "Allow"
      Action:
        - kinesis:GetRecords
        - kinesis:GetShardIterator
        - kinesis:DescribeStream
        - kinesis:ListStreams
      Resource:
        - Fn::GetAtt:
          - cubeBuilderKinesis
          - Arn

package:
  exclude:
    - node_modules/**
    - package-lock.json
    - cube_builder_aws/__pycache__/**
    - cube_builder_aws/utils/__pycache__/**

functions:
  app:
    handler: wsgi.handler
    timeout: 720
    memorySize: 512
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  app_stream: 
    handler: app.continue_process
    timeout: 720
    memorySize: 3008
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - cubeBuilderQueue
              - Arn
      - stream:
          type: kinesis
          batchSize: 50
          arn:
            Fn::GetAtt:
              - cubeBuilderKinesis
              - Arn

resources:
  Resources:
    cubeBuilderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: cubeBuilderQueue
        VisibilityTimeout: 720
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - cubeBuilderQueueDLQ
              - Arn
          maxReceiveCount: 1

    cubeBuilderQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        VisibilityTimeout: 500
        QueueName: cubeBuilderQueueDLQ

    cubeBuilderKinesis:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: cubeBuilderKinesis
        ShardCount: 1